## Class exercise
Given the below dictionarys find out where each of the 4 people find the cheapest shopping according to their needs.
```python
shoppers = {
'Paula':{'Is':4,'Juice':2,'Kakao':3,'Lagkager':2},
'Peter':{'Is':2,'Juice':5,'Kakao':0, 'Lagkager':4},
'Pandora':{'Is':5,'Juice':3, 'Kakao':4, 'Lagkager':5},
'Pietro':{'Is':1,'Juice':8, 'Kakao':9, 'Lagkager':1}
}
shop_prices = {
    'Netto': {'Is':10.50,'Juice':2.25,'Kakao':4.50,'Lagkager':33.50},
    'Fakta': {'Is':4.00,'Juice':4.50,'Kakao':6.25,'Lagkager':20.00}
}
```
Hint: you can use pandas and Transpose to create dataframe: `pd.DataFrame(shoppers).T` to get the necessary shape of the dataframe/matrix. Also use df.to_numpy() to changes a Pandas DataFrame df into a numpy ndarray with only the numeric data


In [2]:
shoppers = {
'Paula':{'Is':4,'Juice':2,'Kakao':3,'Lagkager':2},
'Peter':{'Is':2,'Juice':5,'Kakao':0, 'Lagkager':4},
'Pandora':{'Is':5,'Juice':3, 'Kakao':4, 'Lagkager':5},
'Pietro':{'Is':1,'Juice':8, 'Kakao':9, 'Lagkager':1}
}
shop_prices = {
    'Netto': {'Is':10.50,'Juice':2.25,'Kakao':4.50,'Lagkager':33.50},
    'Fakta': {'Is':4.00,'Juice':4.50,'Kakao':6.25,'Lagkager':20.00}
}

In [48]:
import pandas as pd
import numpy as py

df_shoppers = pd.DataFrame(shoppers).T
df_prices = pd.DataFrame(shop_prices)

shoppers_ndarray = df_shoppers.to_numpy()
prices_ndarray = df_prices.to_numpy()

In [50]:
prices_ndarray

array([[10.5 ,  4.  ],
       [ 2.25,  4.5 ],
       [ 4.5 ,  6.25],
       [33.5 , 20.  ]])

In [49]:
shoppers_ndarray

array([[4, 2, 3, 2],
       [2, 5, 0, 4],
       [5, 3, 4, 5],
       [1, 8, 9, 1]])

In [51]:
shoppers_ndarray.dot(prices_ndarray)

array([[127.  ,  83.75],
       [166.25, 110.5 ],
       [244.75, 158.5 ],
       [102.5 , 116.25]])