## Class exercise 1: table
![](../images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [6]:
import numpy as np

table = np.arange(10,30).reshape(4,5)
table

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [7]:
#yellow
table[0,0]

10

In [11]:
#red
table[0,1:4]

array([11, 12, 13])

In [13]:
#Light blue
table[::,1::2]

array([[11, 13],
       [16, 18],
       [21, 23],
       [26, 28]])

In [14]:
#dark blue
table[0::2,-1]

array([14, 24])

![](../images/cube.png)

## Class exercise 2: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [17]:
cube = np.arange(0, 27).reshape((3, 3, 3))
cube

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
#Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
cube[1,1,::]

array([12, 13, 14])

In [19]:
#Slice out [3 12 21].
cube[::,1,0]

array([ 3, 12, 21])

In [20]:
#Slice out all y-values where x is 2 and z is 0.
cube[0,::,2]

array([2, 5, 8])

### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6


In [21]:
data = np.arange(1,101).reshape(10,10)

In [58]:
even = np.where((data%2==0))
data[even]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [67]:
six = np.where(data%10==6)
data[six]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])