## Class exercise 1: table
![slicing](../images/numpy_slice_ex.png)
- on the above image find the 5 different slicings using only the array slicing notation

In [1]:
import numpy as np

table = np.arange(10,30).reshape(4,5)
table

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [2]:
#yellow
table[0,0]


10

In [11]:
#red
table[0,1:4]

array([11, 12, 13])

In [3]:
#Light blue
table[:,1::2]

array([[11, 13],
       [16, 18],
       [21, 23],
       [26, 28]])

In [4]:
#dark blue
table[0::2,-1]

array([14, 24])

In [6]:
#green
table[0:3,2]

array([12, 17, 22])

![](../images/cube.png)

## Class exercise 2: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [17]:
cube = np.arange(0, 27).reshape((3, 3, 3))
cube

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [18]:
#Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
cube[1,1,::]

array([12, 13, 14])

In [19]:
#Slice out [3 12 21].
cube[::,1,0]

array([ 3, 12, 21])

In [20]:
#Slice out all y-values where x is 2 and z is 0.
cube[0,::,2]

array([2, 5, 8])

### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6


In [8]:
data = np.arange(1,101).reshape(10,10)

In [11]:
even = [data%2==0]
data[even]

/tmp/ipykernel_114/2614967736.py:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data[even]


array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [67]:
six = np.where(data%10==6)
data[six]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

## Exercise numpy and csv

1. load the csv file: befkbhalderstatkode.csv into a numpy ndarray
2. How many german children of 0 years were there in Copenhagen in 2015?
3. create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
4. create a new function like previous so that it can sum values for all ages if age is not provided to the function
5. further add functionality to sum values if citizenship or area was not provided to function.
6. create a new function that can also give average values for each year if year whas not provided.
7. create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
8. Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
9. Find out what age most French people have in 2015

In [4]:
import numpy as np
filename = './../data/befkbhalderstatkode.csv'

bef_stats_df = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
dd = bef_stats_df


In [5]:
mask = np.where((dd[:,0] == 2015) & (dd[:,3] == 5180) & (dd[:,2] == 0 ))
dd[mask]



array([[2015,    1,    0, 5180,    3],
       [2015,    2,    0, 5180,    5],
       [2015,    3,    0, 5180,    7],
       [2015,    4,    0, 5180,    1],
       [2015,    5,    0, 5180,    1],
       [2015,    6,    0, 5180,    2],
       [2015,    8,    0, 5180,    2],
       [2015,    9,    0, 5180,    6],
       [2015,   10,    0, 5180,    8]], dtype=uint64)

In [6]:
np.sum(dd[mask][:,4])

35

create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data

In [28]:
def get_pop(AAR,BYDEL,ALDER,STATKODE):
    mask = np.where((dd[:,0] == AAR) & (dd[:,1] == BYDEL)  & (dd[:,3] == STATKODE) & (dd[:,2] == ALDER ))
    return dd[mask]


In [29]:
get_pop(2015,1,15,5180)

array([[2015,    1,   15, 5180,    1]], dtype=uint64)

create a new function like previous so that it can sum values for all ages if age is not provided to the function

In [41]:
def get_pop_adv(AAR,BYDEL,STATKODE,ALDER=None):
    year = (dd[:,0] == AAR)
    city_part = (dd[:,1] == BYDEL)
    state_code = (dd[:,3] == STATKODE)
    
    if ALDER != None:
        age = (dd[:,2] == ALDER )
        return dd[year & city_part & age & state_code]
    else:
        return np.sum(dd[year & city_part & state_code])



In [43]:
get_pop_adv(2015,1,5100,10)

array([[2015,    1,   10, 5100,  404]], dtype=uint64)

further add functionality to sum values if citizenship or area was not provided to function.